name: Build & Deploy JSON to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build JSON from Google Sheets
        env:
          SHEET_ID: ${{ vars.SHEET_ID }}
        run: |
          python -m pip install --upgrade pip
          python scripts/fetch_and_build.py
          ls -la data

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './data'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
