name: Fetch and build data

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  fetch-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python scripts/fetch_and_build.py
      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data
